title: 'Section syndicale Almond'
masthead_title: " "
subtitle: ""
email: contact@printemps-ecologique.fr
description: >- 
  Section syndicale du Printemps écologique dans l'entreprise Almond
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ["_pages"]

# Build settings
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

date_format: "%Y-%m-%d"
encoding: utf-8

# Theme specific parameters
minimal_mistakes_skin: "mint"
locale: fr-FR

logo: "/assets/images/logo_pe-340x180.png"

atom_feed:
  hide: true

search: true

footer:
  links:
    - label: ""
      icon: "fa-solid fa-hand-fist"
      url: "https://www.printemps-ecologique.fr/"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ecosyndicat"
    - label: ""
      icon: "fa-brands fa-linkedin-in"
      url: "https://www.linkedin.com/company/printemps-%C3%A9cologique/"
    - label: ""
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/Printemps-Ecologique-111299223749588/"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/printemps.ecologique/?hl=fr-ca"

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      words_per_minute: 250
  - scope:
      path: ""
    values:
      show_title: true

